# Light simulator scenario - 1 sensor, 4 attributes
# Moderate load, good for development testing

connectors:
  sim_connector_1:
    connector_id: "sim_connector_1"
    connector_name: "Light_Monitor"
    sensors:
      sim_patient_1:
        sensor_id: "sim_patient_1"
        sensor_name: "Patient_Monitor_1"
        attributes:
          heartrate:
            attribute_id: "heartrate"
            sensor_type: "heartrate"
            batch_size: 5
            batch_window: 1000
            duration: 0
            sampling_rate: 1
            heart_rate: 72
            respiratory_rate: 14
            dummy_data: true
          spo2:
            attribute_id: "spo2"
            sensor_type: "spo2"
            batch_size: 5
            batch_window: 1000
            duration: 0
            sampling_rate: 1
            min_value: 95
            max_value: 99
            dummy_data: true
          temperature:
            attribute_id: "temperature"
            sensor_type: "temperature"
            batch_size: 1
            batch_window: 5000
            duration: 0
            sampling_rate: 0.2
            min_value: 36.5
            max_value: 37.2
            dummy_data: true
          blood_pressure_sys:
            attribute_id: "blood_pressure_sys"
            sensor_type: "blood_pressure"
            batch_size: 1
            batch_window: 10000
            duration: 0
            sampling_rate: 0.1
            min_value: 115
            max_value: 125
            dummy_data: true
