# Minimal simulator scenario - 1 sensor, 2 attributes
# Use for basic testing and low system load

connectors:
  sim_connector_1:
    connector_id: "sim_connector_1"
    connector_name: "Minimal_Monitor"
    sensors:
      sim_patient_1:
        sensor_id: "sim_patient_1"
        sensor_name: "Patient_Basic"
        attributes:
          heartrate:
            attribute_id: "heartrate"
            sensor_type: "heartrate"
            batch_size: 5
            batch_window: 1000
            duration: 0
            sampling_rate: 1
            heart_rate: 72
            respiratory_rate: 14
            dummy_data: true
          spo2:
            attribute_id: "spo2"
            sensor_type: "spo2"
            batch_size: 5
            batch_window: 1000
            duration: 0
            sampling_rate: 1
            min_value: 95
            max_value: 99
            dummy_data: true
