# Single Person Demo - 1 person with 5 sensors
# Use case: Demo, detailed monitoring of one individual

connectors:
  scenario_single_person:
    connector_id: "scenario_single_person"
    connector_name: "Single_Person_Demo"
    sensors:
      person_1:
        sensor_id: "person_1"
        sensor_name: "Person1"
        attributes:
          # High frequency - ECG waveform
          ecg:
            attribute_id: "ecg"
            sensor_type: "ecg"
            batch_size: 50
            batch_window: 500
            duration: 0
            sampling_rate: 50
            heart_rate: 72
            dummy_data: true
          # Medium frequency - vital signs
          heartrate:
            attribute_id: "heartrate"
            sensor_type: "heartrate"
            batch_size: 5
            batch_window: 1000
            duration: 0
            sampling_rate: 1
            heart_rate: 72
            dummy_data: true
          spo2:
            attribute_id: "spo2"
            sensor_type: "spo2"
            batch_size: 5
            batch_window: 1000
            duration: 0
            sampling_rate: 1
            min_value: 96
            max_value: 99
            dummy_data: true
          # Low frequency - slow changing
          temperature:
            attribute_id: "temperature"
            sensor_type: "temperature"
            batch_size: 1
            batch_window: 60000
            duration: 0
            sampling_rate: 0.017
            min_value: 36.4
            max_value: 37.0
            dummy_data: true
          blood_pressure_sys:
            attribute_id: "blood_pressure_sys"
            sensor_type: "blood_pressure"
            batch_size: 1
            batch_window: 60000
            duration: 0
            sampling_rate: 0.017
            min_value: 118
            max_value: 128
            dummy_data: true
