# Single Person Demo - 1 person with comprehensive sensor suite
# Use case: Demo, detailed monitoring of one individual
#
# Realistic Sampling Rates:
# - ECG: 100Hz (batch_size: 100, batch_window: 1000ms)
# - Heartrate/SpO2: 0.2Hz (every 5 seconds)
# - Temperature/Blood Pressure: 0.017Hz (once per minute)
# - Battery: 0.1Hz (every 10 seconds)

connectors:
  scenario_single_person:
    connector_id: "scenario_single_person"
    connector_name: "Single_Person_Demo"
    sensors:
      person_1:
        sensor_id: "person_1"
        sensor_name: "Sim_Person1"
        attributes:
          # High frequency - ECG waveform (100Hz)
          ecg:
            attribute_id: "ecg"
            sensor_type: "ecg"
            batch_size: 100
            batch_window: 1000
            duration: 0
            sampling_rate: 100
            heart_rate: 72
            dummy_data: true
          # Low frequency - vital signs (0.2Hz = every 5 seconds)
          heartrate:
            attribute_id: "heartrate"
            sensor_type: "heartrate"
            batch_size: 1
            batch_window: 5000
            duration: 0
            sampling_rate: 0.2
            heart_rate: 72
            dummy_data: true
          spo2:
            attribute_id: "spo2"
            sensor_type: "spo2"
            batch_size: 1
            batch_window: 5000
            duration: 0
            sampling_rate: 0.2
            min_value: 96
            max_value: 99
            dummy_data: true
          # Very low frequency - slow changing (0.017Hz = once per minute)
          temperature:
            attribute_id: "temperature"
            sensor_type: "temperature"
            batch_size: 1
            batch_window: 60000
            duration: 0
            sampling_rate: 0.017
            min_value: 36.4
            max_value: 37.0
            dummy_data: true
          blood_pressure_sys:
            attribute_id: "blood_pressure_sys"
            sensor_type: "blood_pressure"
            batch_size: 1
            batch_window: 60000
            duration: 0
            sampling_rate: 0.017
            min_value: 118
            max_value: 128
            dummy_data: true
          # Battery status (0.1Hz = every 10 seconds)
          battery:
            attribute_id: "battery"
            sensor_type: "battery"
            batch_size: 1
            batch_window: 10000
            duration: 0
            sampling_rate: 0.1
            min_value: 65
            max_value: 90
            dummy_data: true
