name: Fly Deploy
on:
  push:
    branches:
      - main    # change to main if needed
      
  
jobs:
  deploy:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      MIX_ENV: "prod"
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      #- run: flyctl auth docker --debug
      #- run: docker build -t sensocto .
      #- run: docker tag sensocto registry.fly.io/sensocto
      #- run: docker push registry.fly.io/sensocto
      
      #- run: flyctl deploy --local-only --debug
      - run: flyctl deploy --build-arg REVISION=${{ github.sha }} --depot --remote-only
      # --remote-only
        